version: '3'
services:
  rokcet-app:
    image: 'rockets-ws'
    container_name: 'rockets-service-app'
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - rockets-database
    environment:
      - MONGO_HOST=rockets-database
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 20s
      retries: 5
  rockets-database:
    image: 'mongo:5.0.6'
    container_name: 'rockets-service-mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=rockets
      - MONGO_INITDB_ROOT_USERNAME=superuser
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017-27019:27017-27019'